# Generated by Django 3.2.6 on 2021-10-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated',
        ),
    ]
