# Generated by Django 3.2.6 on 2021-10-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211026_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to='products.userdetails'),
        ),
    ]
