# Generated by Django 3.2.6 on 2021-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211026_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedorder',
            name='userdetail',
        ),
        migrations.AddField(
            model_name='confirmedorder',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
    ]
