# Generated by Django 3.2.6 on 2021-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211026_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorder',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
